

export const productList = [
  {
    id: "Raw-Shea-Butter-Hydrate-Repair-Shampoo",
    nameGeo: "ნედლი შიის კარაქის ჰიდრატი/აღმდგენი შამპუნი",
    nameEng: "Raw Shea Butter Hydrate & Repair Shampoo",
    price: "34.00",
    images: [
      "https://i.postimg.cc/v8hwNtfx/IMG-0751.png",
      "https://i.postimg.cc/kXMqJpqy/IMG-0760-1.png",
      "https://i.postimg.cc/v8hwNtfx/IMG-0751.png",
      "https://i.postimg.cc/FH7vckfd/IMG-0757.png",

    ],
    inStock: 2,
    fastDelivery: true,
    ratings: 4,
    descriptionGeo:"იდეალურია მათთვის ვინც ხშირად იღებავს, მექანიკურად ან ქიმიურად ისწორებს/იხვევს ან იღიავებს თმას, იყენებს თმის უთოს და ფენს ხშირად და ზოგადად თმას ხშირად აყენებს ზიანს მშვენიერების მისაღწევად. შიის კარაქის შამპუნი მრავალ დადებით გავლენას ახდენს თმაზე, შიის კარაქის ბუნებრივი და მკვებავი თვისებების გამო, ის უზრუნველყოფს თმის ღრმა დატენიანებას ცხიმოვანი მჟავებითა და ისეთი აუცილებელი ვიტამინებით, როგორიცაა A და E ვიტამინები. ყოველივე ხსენებული ხელს უწყობს თმის ტენიანობის შეკავებას, სიმშრალის შემცირებას და გაფუჭების პრევენციას, აღნიშნული შამპუნი არის ულტრა ჰიდრატი და აღმდგენი, რაც გულისხმობს იმას რომ შამპუნის შემადგენლობა განაპირობებს მის ძირითად თვისებას, რომ აღადგინოს ქიმიურად დაზიანებული ან დამუშავებული თმა უმოკლეს ვადაში (შეღებვა, თმის ხელოვნური დახვევა ან გასწორება, თმის ქიმიური გასწორება,თმის გაღიავება, არასწორი გამოყენება თმის უთოსი ან ფენის და ასე შემდეგ...). გარდა ამისა, შიის კარაქი არბილებს თმის კუტიკულას, ამცირებს უხეშ და გაყოფილ ბოლოებს, რაც იწვევს წინაპირობაა გლუვი, უფრო მორჩილი თმის. გარდა ამისა, შის კარაქი აძლიერებს თმის ღერს, ხდის მას უფრო ელასტიურს და ნაკლებად მიდრეკილს მსხვრევისკენ. ის ასევე ქმნის დამცავ ბარიერს თმაზე, იცავს მას გარემოს დაზიანებისგან, როგორიცაა დაბინძურება, ულტრაიისფერი სხივები და მკაცრი ამინდის პირობები. ითვლება, რომ შის კარაქი ასტიმულირებს თმის ფოლიკულებს და პოტენციურად ხელს უწყობს თმის ზრდას. მათთვის, ვისაც აქვს მგრძნობიარე ან გაღიზიანებული სკალპი, შის კარაქის შამპუნი მათთვის იდეალურია, ვინაიდან აქვს ანთების საწინააღმდეგო და დამამშვიდებელი თვისებები თმისთვის. ის ზოგადად თავსებადია ყველა ტიპის თმასთან, მათ შორის ბუნებრივ და ფერად დამუშავებულ თმასთან, რადგან არაკომედოგენურია. საუკეთესო შედეგისთვის გამოიყენეთ Koco Mist / შიის კარაქის ჰიდრატ და აღმდგენ ბალზამთან ერთად. ",
    descriptionEng: "Shea butter shampoo can have several positive impacts on hair due to the natural and nourishing properties of Shea butter. It provides deep moisturization, thanks to its richness in fatty acids and essential vitamins like A and E. This helps lock in moisture, reducing dryness and preventing breakage. Additionally, Shea butter smooths out the hair cuticle, reducing frizz and split ends, leading to smoother, more manageable hair. Furthermore, Shea butter strengthens the hair shaft, making it more resilient and less prone to breakage. It also forms a protective barrier on the hair, shielding it from environmental damage such as pollution, UV rays, and harsh weather conditions. Shea butter is believed to stimulate hair follicles, potentially promoting hair growth, although results may vary. For those with sensitive or irritated scalps, Shea butter's anti-inflammatory and soothing properties can provide relief. It is generally compatible with all hair types, including natural, relaxed, and color-treated hair, as it is non-comedogenic. For best results pair with Koco Mist / RAW SHEA BUTTER HYDRATE REPAIR CONDITIONER ",
    quantity: 1,
    category: "Shampoo",
  },
  {
    id: "Raw-Shea-Butter-Hydrate-Repair-Conditioner",
    nameGeo: "ნედლი შიის კარაქის ჰიდრატი/აღმდგენი ბალზამი ",
    nameEng: "Raw Shea Butter Hydrate & Repair Conditioner",
    price: "34.00",
    images: [
      "https://i.postimg.cc/BvHdcTJ6/IMG-0749.png",
      "https://i.postimg.cc/5tzMKcSf/IMG-0759.png",
      "https://i.postimg.cc/K8gVxPkN/IMG-0738.pngg",
      "https://i.postimg.cc/43gVkk9g/hq-shea-conditioner.jpg",

    ],
    inStock: 20,
    fastDelivery: true,
    ratings: 4,
    descriptionGeo:"შიის ბალზამს აქვს უამრავი დადებითი თვისება კანისა და თმისთვის, ბუნებრივი და მკვებავი თვისებების წყალობით. ის უზრუნველყოფს ღრმა დატენიანებას ცხიმოვანი მჟავებითა და ისეთი აუცილებელი ვიტამინებით, როგორიცაა A და E. ეს ხელს უწყობს თმის ტენიანობის შეკავებას, სიმშრალის შემცირებას და მსხვრევის თავიდან აცილებას. გარდა ამისა, შიის ბალზამი არბილებს თმის კუტიკულას და გაყოფილ ბოლოებს, რაც თმას უფრო გლუვს და მორჩილს ხდის. გარდა ამისა, ის აძლიერებს თმის ღერს, ხდის მას უფრო ელასტიურს და ნაკლებად მიდრეკილს მსხვრევისკენ. ის ასევე ქმნის დამცავ ბარიერს თმაზე, იცავს მას გარემო დაზიანებისგან, როგორიცაა დაბინძურება, ულტრაიისფერი სხივები და მკაცრი ამინდის პირობები. ითვლება, რომ შიის ბალზამი ასტიმულირებს თმის ფოლიკულებს და პოტენციურად ხელს უწყობს თმის ზრდას. მათთვის, ვისაც აქვს მგრძნობიარე ან გაღიზიანებული კანი, შიის ბალზამის ანთების საწინააღმდეგო და დამამშვიდებელი თვისებების ხარჯზე თმას და კანს ბალზამი მოჰგვრის შვებას. ის ზოგადად თავსებადია ყველა ტიპის კანთან, რაც მას უნივერსალურ ვარიანტად აქცევს კანისა და თმის დამატენიანებლად და მკვებავად. საუკეთესო შედეგისთვის, გამოიყენეთ  Koco Mist / შიის ჰიდრატ და მკვებავ შამპუნთან ერთად.",
    descriptionEng: "Shea balsam can offer numerous benefits for the skin and hair, thanks to its natural and nourishing properties. It provides deep moisturization due to its richness in fatty acids and essential vitamins like A and E. This helps in locking in moisture, reducing dryness, and preventing breakage. Additionally, shea balsam smooths out the hair cuticle, reducing frizz and split ends, leading to smoother, more manageable hair. Moreover, it strengthens the hair shaft, making it more resilient and less prone to breakage. It also forms a protective barrier on the hair, shielding it from environmental damage such as pollution, UV rays, and harsh weather conditions. Shea balsam is believed to stimulate hair follicles, potentially promoting hair growth, although results may vary. For those with sensitive or irritated skin, shea balsam's anti-inflammatory and soothing properties can provide relief. It is generally compatible with all skin types, making it a versatile option for moisturizing and nourishing the skin and hair For best results pair with Koco Mist / RAW SHEA HYDRATE REPAIR SHAMPOO. ",
    quantity: 1,
    category: "Balsam",
  },
  {
    id: "Virgin-Coconut-Oil-Daily-Hydration-Shampoo",
    nameGeo: "ქოქოსის ზეთის დღიული ჰიდრატი შამპუნი",
    nameEng: "Virgin Coconut Oil Daily Hydration Shampoo",
    price: "34.00",
    images: [
      "https://i.postimg.cc/RZyBTCfP/IMG-0754.png",
      "https://i.postimg.cc/tTHGLrBW/IMG-0758.png",
      "https://i.postimg.cc/TwxBkKPc/IMG-0746.png",
      
      "https://i.postimg.cc/vHmwFxtq/IMG-0750.png",

    ],
    inStock: 13,
    fastDelivery: false,
    ratings: 4,
    descriptionGeo:"იდეალურია მათთვის ვისაც აწუხებს ქერტლი. ქოქოსის ზეთის უამრავი სასარგებლო შედეგი მოაქვს თმისთვის, ქოქოსის ზეთის ბუნებრივი და მკვებავი თვისებების გამო, ის უზრუნველყოფს თმის ღრმა დატენიანებას ცხიმოვანი მჟავების და ისეთი აუცილებელი ვიტამინების მაღალი შემცველობის გამო, როგორიცაა A და E ვიტამინები. ეს ხელს უწყობს ტენიანობის შეკავებას, სიმშრალის შემცირებას და მსხვრევას. გარდა ამისა, ქოქოსის ზეთი არბილებს თმის კუტიკულას და ამცირებს  გაყოფილ ბოლოებს, რის შედეგადაც თმა ხდება უფრო გლუვი და უფრო მოქნილი. ქოქოსის ზეთის ზოგიერთ ბალზამს შეიძლება ჰქონდეს დამატებითი ინგრედიენტები, რომლებიც იცავს სითბოს სტილის ხელსაწყოებისგან, როგორიცაა ბრტყელი უთოები და ტალღოვანი უთოები.ს:ჩვენი ქოქოსის ზეთის შამპუნს აქვს დამატებითი ინგრედიენტები, რომლებიც იცავს თმის გასასწორებელი და გასამშრალებელი ხელსაწყოებისგან, როგორიცაა ბრტყელი უთოები და თმის ფენი. შამპუნის მთავარი ინგრედიენტი მკურნალობს ქერტლს და სკალპს: ქოქოსის ზეთის სოკოს საწინააღმდეგო თვისებები დაგეხმარებათ ქერტლის წინააღმდეგ ბრძოლაში და სკალპის გარკვეულ პრობელემებთან, რომლებიც გამოწვეულია სოკოებით ან ბაქტერიებით. ქოქოსის ზეთი აძლევს თმას ჯანსაღ ბზინვარებას და ბზინვარებას. ის შეიძლება გამოყენებულ იქნას, როგორც თმის შრატების ბუნებრივი ალტერნატივა, გარდა ამისა, ქოქოსის ზეთი აძლიერებს თმის ღერს, აძლიერებს ელასტიურობას რაც განაპირობებს თმას იყოს უფრო მარტივად დავარცხნადი და ამცირებს თმის მსხვრევის ალბათობას. ის ასევე ქმნის დამცავ ბარიერს თმაზე, იცავს მას გარემო სტრესებისგან, როგორიცაა დაბინძურება, ულტრაიისფერი სხივები და მკაცრი ამინდის პირობები. ითვლება, რომ ქოქოსის ზეთი ხელს უწყობს თმის ზრდას თმის ფოლიკულების სტიმულირებით. ზოგადად თავსებადია ყველა ტიპის თმასთან, მათ შორის ბუნებრივ და ფერად დამუშავებულ თმასთან, რაც მას იდეალურ პროდუქტად ხდის თმის კვებისთვის და სიჯანსაღის შესანარჩუნებლად. საუკეთესო შედეგისთვის გამოიყენეთ Koco Mist / ქოქოსის ზეთი დღიურ დამატენიანებელ ბალზამთან ერთად. .",
    descriptionEng:"Coconut oil shampoo can provide a range of benefits for hair, owing to the natural and nourishing properties of coconut oil. It offers deep moisturization due to its high content of fatty acids and essential vitamins such as A and E. This aids in locking in moisture, reducing dryness, and preventing breakage. Additionally, coconut oil smooths the hair cuticle, lessening frizz and split ends, resulting in smoother, more manageable hair. Furthermore, coconut oil strengthens the hair shaft, enhancing resilience and reducing the likelihood of breakage. It also forms a protective barrier on the hair, shielding it from environmental stressors like pollution, UV rays, and harsh weather conditions. Coconut oil is believed to promote hair growth by stimulating hair follicles, although individual results may vary. For those with sensitive or irritated scalps, coconut oil's anti-inflammatory and soothing properties can offer relief. It is generally compatible with all hair types, including natural, relaxed, and color-treated hair, making it a versatile choice for nourishing and maintaining healthy hair. For best results pair with Koco Mist / COCONUT OIL DAILY HYDRATION CONDITIONER",
    quantity: 1,
    category: "Shampoo",
  },
  {
    id: "Virgin-Coconut-Oil-Daily-Hydration-Conditioner",
    nameGeo: "ქოქოსის ზეთის დღიული ჰიდრატი ბალზამი",
    nameEng: "Virgin Coconut Oil Daily Hydration Conditioner",
    price: "34.00",
    images: [
      "https://i.postimg.cc/SRT5NVfZ/IMG-0742.png",
      "https://i.postimg.cc/G3q6Qhnk/IMG-0741.png",
      "https://i.postimg.cc/GthVC6G8/IMG-0743.png",
      "https://i.postimg.cc/Dy0HYk7R/IMG-0740.png",

    ],
    inStock: 17,
    fastDelivery: false,
    ratings: 4,
    descriptionGeo:"ქოქოსის ზეთის ბალზამი უზრუნველყოფს ღრმა დატენიანებას და კვებას კანისა და თმისთვის. მდიდარია ცხიმოვანი მჟავებით, A და E ვიტამინებით, ბლოკავს ტენიანობას, ამცირებს სიმშრალეს და აფერხებს მსხვრევას. ის არბილებს თმის კუტიკულებს, მინიმუმამდე აქცევს აწეულ და გაყოფილ ბოლოებს, რის შედეგადაც თმა ხდება უფრო გლუვი და უფრო მოქნილი. გარდა ამისა, ქოქოსის ზეთის ბალზამი აძლიერებს თმის ღერებს, აძლიერებს ელასტიურობას და ამცირებს მსხვრევას. იგი ქმნის დამცავ ბარიერს, იცავს დაბინძურებისგან, ულტრაიისფერი სხივებისა და მკაცრი ამინდისგან. ითვლება, რომ ასტიმულირებს თმის ფოლიკულებს, შეიძლება ხელი შეუწყოს ზრდას, თუმცა შედეგები განსხვავებულია. მათთვის, ვისაც აქვს მგრძნობიარე ან გაღიზიანებული კანი, მისი ანთების საწინააღმდეგო თვისებები უზრუნველყოფს თმის და კანის შვებას. თავსებადია ყველა ტიპის კანთან, ბალზამი არის საუკეთესო დამატენიანებელი და მკვებავი. საუკეთესო შედეგისთვის გამოიყენეთ / KOCO MIST ქოქოსის ზეთის დამატენიანებელ შამპუნთან ერთად.",
    descriptionEng:"Coconut oil balsam offers deep moisturization and nourishment for skin and hair. Rich in fatty acids, vitamins A and E, it locks in moisture, reducing dryness and preventing breakage. It smooths hair cuticles, minimizing frizz and split ends, resulting in smoother, more manageable hair. Furthermore, coconut oil balsam strengthens hair shafts, enhancing resilience and reducing breakage. It forms a protective barrier, shielding against pollution, UV rays, and harsh weather. Believed to stimulate hair follicles, it may promote growth, though results vary. For those with sensitive or irritated skin, its anti-inflammatory properties provide relief. Compatible with all skin types, it's a versatile choice for moisturizing and nourishing. For the best result pair with / KOCO MIST COCONUT OIL DAILY HYDRATION SHAMPOO",
    quantity: 1,
    category: "Balsam",
  },
  {
    id: "Jamaican-Black-Castor-Oil-Strengthen&Restore-Shampoo",
    nameGeo: "იამაიკური შავი აბუსალათინის ზეთის შამპუნი",
    nameEng: "Jamaican Black Castor Oil Shampoo",
    price: "34.00",
    images: [
      "https://i.postimg.cc/2SPsZcRM/IMG-0745.jpg",
      "https://i.postimg.cc/HsPDpWSp/IMG-0747.jpg",
      "https://i.postimg.cc/xd84rdTm/pebblely-3.jpg",
      "https://i.postimg.cc/Kv7VBVH1/pebblely-4.jpg",
    ],
    inStock: 10,
    fastDelivery: false,
    ratings: 4,
    descriptionGeo:" იდეალურია მათთვის ვისაც აწუხებს თმის ცვენა ან გათხელება. იამაიკური შავი აბუსალათინის ზეთის შამპუნი უზრუნველყოფს თმის ღრმა წმენდას და კვებას. გამდიდრებულია ომეგა ცხიმოვანი მჟავებით, აძლიერებს თმას და ხელს უწყობს ჯანსაღ ზრდას. იამაიკური აბუსალათინის ზეთი მრავალ კულტურაში ათასობით წლის მანძილზე გამოიყენებოდა თმის გათხელებასთან და მის ცვენასთან საბრძოლველად, ისტორიული გამოცდილება ამტკიცებს, რომ იამაიკური აბუსალათინის ზეთის გამოყენება თხელ ადგილებზე ან თავის უთმო ნაწილზე ხელს უწყობს თმის ზრდას. ასევე ატენიანებს სკალპს, ამცირებს სიმშრალეს და ქერტლს. გარდა ამისა, ის ხელს უწყობს დაზიანებული თმის აღდგენას. გარდა ამისა, იამაიკური შავი აბუსალათინის ზეთის შამპუნი აუმჯობესებს თმის ტექსტურას, ხდის მას უფრო გლუვს და მორჩილს. ის ასტიმულირებს თმის ფოლიკულებს, რაც პოტენციურად იწვევს ზრდის ზრდას. ეს შამპუნი თავსებადია თმის სხვადასხვა ტიპებთან. მათთვის, ვისაც აქვს მგრძნობიარე სკალპი, მისი დამამშვიდებელმი თვისებები ხსნის კანისა და თმის გაღიზიანებას. ეს არის იდეალური არჩევანი ჯანსაღი და ცოცხალი თმის შესანარჩუნებლად. საუკეთესო შედეგისთვის შეუთავსეთ Koco Mist / იამაიკური შავი აბუსალათინის ზეთის ბალზამს. .",
    descriptionEng: "Jamaican black castor oil shampoo offers deep cleansing and nourishment for hair. Enriched with omega fatty acids, it strengthens hair and promotes healthy growth. It also moisturizes the scalp, reducing dryness and flakiness. Additionally, it helps in repairing damaged hair and preventing breakage. Furthermore, Jamaican black castor oil shampoo improves hair texture, making it smoother and more manageable. It stimulates hair follicles, potentially leading to increased growth. This shampoo is compatible with various hair types and is known for its natural, chemical-free ingredients. For those with sensitive scalps, its soothing properties can provide relief from irritation. It's a versatile choice for maintaining healthy and vibrant hair. For best results pair with Koco Mist / JAMAICAN BLACK CASTOR OIL STRENGTHEN & RESTORE CONDITIONER",
    quantity: 1,
    category: "Shampoo",
  },
  {
    id: "Jamaican-Black-Castor-Oil-Strengthen&Restore-Conditioner",
    nameGeo:"იამაიკური შავი აბუსალათინის ზეთის ბალზამი",
    nameEng: "Jamaican Black Castor Oil Conditioner",
    price: "34.00",
    images: [
      "https://i.postimg.cc/fyCs7xjX/IMG-0756.jpg",
      "https://i.postimg.cc/wMq8B18B/IMG-0752.png",
      "https://i.postimg.cc/ZnwkvJ4x/IMG-0753.png",
      "https://i.postimg.cc/ryNqLkXm/IMG-0755.jpg",
    ],
    inStock: 5,
    fastDelivery: true,
    ratings: 4,
    descriptionGeo:"იამაიკური შავი აბუსალათინის ზეთის ბალზამი უზრუნველყოფს თმის ღრმა დატენიანებას და კვებას კანისა და თმისთვის. იდეალურია მათთვის ვისაც აწუხებს თმების გათხელება და ცვენის პრობლემები. მდიდარია ცხიმოვანი მჟავებით, A და E ვიტამინებით, ამცირებს სიმშრალეს და აფერხებს მსხვრევადობას. ის არბილებს თმის კუტიკულებს, მინიმუმამდე აქცევს აწეულ და გაყოფილ ბოლოებს, რის შედეგადაც თმა ხდება უფრო გლუვი და  უფრო მოქნილი. გარდა ამისა, იამაიკური შავი აბუსალათინის ზეთის ბალზამი აძლიერებს თმის ღერებს, აძლიერებს ელასტიურობას და ამცირებს მსხვრევას. იგი ქმნის დამცავ ბარიერს დაბინძურებისგან, ულტრაიისფერი სხივებისა და მკაცრი ამინდისგან. ითვლება, რომ ასტიმულირებს თმის ფოლიკულებს, და ხელს უწყობს თმის ზრდას. თავსებადია ყველა ტიპის კანთან. საუკეთესო შედეგისთვის გამოიყენეთ Koco Mist / იამაიკური შავი აბუსალათინის შამპუნთან.",
    descriptionEng:"Jamaican black castor oil balsam offers deep moisturization and nourishment for skin and hair. Rich in fatty acids, vitamins A and E, it locks in moisture, reducing dryness and preventing breakage. It smooths hair cuticles, minimizing frizz and split ends, resulting in smoother, more manageable hair. Furthermore, Jamaican black castor oil balsam strengthens hair shafts, enhancing resilience and reducing breakage. It forms a protective barrier, shielding against pollution, UV rays, and harsh weather. Believed to stimulate hair follicles, it may promote growth, though results vary. For those with sensitive or irritated skin, its anti-inflammatory properties provide relief. Compatible with all skin types, it's a versatile choice for moisturizing and nourishing. For best results pair with Koco Mist / JAMAICAN BLACK CASTOR OIL SHAMPOO.",
    quantity: 1,
    category: "Balsam",
  },
  {
    id: "Honey-&-Yogurt-Hydrate-&-Repair-Shampoo",
    nameGeo:"თაფლის და იოგურტის ჰიდრატი& აღმდგენი შამპუნი",
    nameEng: "Hydrate & Repair Honey & Yogurt Shampoo",
    price: "34.00",
    images: [
      "https://i.postimg.cc/VL71dWNP/IMG-0761.png",
      "https://i.postimg.cc/d19pgJkc/IMG-0744.png",
      "https://i.postimg.cc/m2nqvXDk/IMG-0739.png",
      "https://i.postimg.cc/w3KZr0Ff/hq-yogurt-shampoo.jpg",

    ],
    inStock: 9,
    fastDelivery: false,
    ratings: 4,
    descriptionGeo: "იდეალურია მათთვის ვისაც აწუხებს თმის ზედმეტი გაცხიმოვნება. შიის დამატენიანებელი მანუკას თაფლისა და იოგურტის შამპუნი  წარმოქმნის მდიდრულ ქაფს, რომელიც ნაზად ასუფთავებს თქვენს ფოლიკულებს. Შამპუნის მაგიური თვისება წარმოადგენს მის უნარს დააბალანსოს თმის pH: იოგურტი რბილად მჟავეა, რაც ხელს უწყობს სკალპის pH-ის დაბალანსებას. ეს განსაკუთრებით სასარგებლოა სკალპის დისბალანსირებული pH-ის მქონე პირებისთვის, რამაც შეიძლება გამოიწვიოს ისეთი პრობლემები, როგორიცაა ქერტლი ან ზედმეტი ცხიმიანობა, ყოველივე ამას ებრძვის კონკრეტული შამპუნი, შესაბამისად რეგულარული მოხმარების შემდგომ იგრძნობთ თმის გაცხიმოვნების პრობლემის მნიშვნელოვან შემცირებას. შამპუნი აგრეთვე გამოირჩევა მისი სურნელით, თაფლის და იოგურტის შამპუნებს ხშირად აქვთ ძალიან სასიამოვნო, ბუნებრივი სურნელი თაფლისა და იოგურტის შემცველობის გამო, რის გამოც იგი წარმოადგენს თმის პარფიუმერიის ბუნებრივ ალტერნატივას. ჩვენი ფორმულა შეიცავს აღმდგენ პროტეინებს და ბზინვარების გამაძლიერებელ ნივთიერებებს. Ჩვენ არ ვეყრდნობით მხოლოდ ამ ძლიერად დამატენიანებელ ტონს და ვუზრუნველყოფთ კიდევ უფრო მეტად დამატენიანებელ და თმის ფოლიკულების სამკურნალო თვისებებით დახუნძლულ ულტრა დამატენიანებელ მანუკას თაფლით. პროტეინი მოდის იოგურტის ექსტრაქტიდან. შამპუნი შეიცავს ბაობაბის ზეთს, ქოქოსის ზეთს და მაფურას ზეთს, რაც აუმჯობესებს სიგლუვეს, ტექსტურას და თმის მმართვადობას. საუკეთესო შედეგის მისაღწევად გამოიყენეთ Koco Mist / ჰიდრად და აღმდგენ თაფლისა და იოგირტუს ბალზამთან ერთად.",
    descriptionEng: "Honey & yogurt mix shampoo provides nourishment and hydration for hair. Packed with vitamins and proteins, it strengthens and revitalizes. It also helps in maintaining a healthy scalp, reducing dryness and flakiness. Additionally, it contributes to smoother and more manageable hair. Furthermore, honey & yogurt mix shampoo improves hair texture and shine. It's a natural option without harsh chemicals. For those with sensitive scalps, it can provide soothing relief. Compatible with various hair types, it's a versatile choice for maintaining. For the best results pair with Koco Mist / HYDRATE & REPAIR HONEY & YOGURT CONDITIONER.",
    quantity: 1,
    category: "Shampoo",
  },
  {
    id: "Honey-&-Yogurt-Hydrate-&-Repair-Conditioner",
    nameGeo: "თაფლის და იოგურტის ჰიდრატი/აღმდგენი ბალზამი",
    nameEng: "Hydrate & Repair Honey & Yogurt Conditioner",
    price: "34.00",
    images: [
      "https://i.postimg.cc/wMq8B18B/IMG-0752.png",
      "https://i.postimg.cc/ZnwkvJ4x/IMG-0753.png",
      "https://i.postimg.cc/CMRRPTbY/honey-yogurt-conditioner-front.png",   
      "https://i.postimg.cc/yNPJYGZR/hq-honey-yogurt-conditioner.jpg",

    ],
    inStock: 11, 
    fastDelivery: true,
    ratings: 4,
    descriptionGeo:"თაფლისა და იოგურტის ბალზამი უზრუნველყოფს თმის ღრმა კვებას. ვიტამინებითა და ცილებით სავსე, აძლიერებს და აცოცხლებს თმის ღერებს. ის განაპირობებს ჯანსაღი სკალპის შენარჩუნებას, ამცირებს სიმშრალეს და ქერტლს. გარდა ამისა, ის თმას ხდის უფრო გლუვს და მორჩილს. Ბალზამს აქვს იდეალური სურნელი რომელიც მომდინარეობს იოგურტის და თაფლის ექსტრაქტისგან, და იდეალურია გაცხიმოვნებასთან საბრძოლველად. გარდა ამისა, თაფლისა და იოგურტის ბალზამი აუმჯობესებს თმის ტექსტურას და ბზინვარებას. ეს ბუნებრივი ალტერნატივაა მავნე ქიმიკატების მიღების მაგივრად თმის მჟავიანობის დაბალანსებისთვის. ბალზამი არის იდეალური არჩევანი ჯანსაღი და ცოცხალი თმის შესანარჩუნებლად. საუკეთესო შედეგისთვის გამოიყენეთ Koco Mist/ ჰიდრატ და აღმდგენ იოგურტის და თაფლის შამპუნთან ერთად.",
    descriptionEng: "Honey & yogurt balsam provides deep nourishment for hair. Packed with vitamins and proteins, it strengthens and revitalizes. It maintains a healthy scalp, reducing dryness and flakiness. Additionally, it contributes to smoother, more manageable hair. Furthermore, honey & yogurt balsam improves hair texture and shine. It's a natural option without harsh chemicals. For those with sensitive scalps, it can provide soothing relief. Compatible with various hair types, it's a versatile choice for maintaining healthy and vibrant hair. For best results pair with Koco Mist / HYDRATE & REPAIR HONEY & YOGURT SHAMPOO",
    quantity: 1,
    category: "Balsam",
  },
  {
    id: "Turmeric-Powder",
    nameGeo: "კურკუმას ფხვნილი",
    nameEng: "Turmeric Powder",
    price: "40.00",
    images: [
      "https://i.postimg.cc/8k6xPsdB/pebblely-10.jpg",
      "https://i.postimg.cc/htp53mgg/pebblely-8.jpg",
      "https://i.postimg.cc/q7FZpdz5/pebblely-9.jpg",
      "https://i.postimg.cc/L8HWTTcN/pebblely-7.jpg",
      
    ],
    inStock: 7,
    fastDelivery: true,
    ratings: 4,
    descriptionGeo:"კურკუმას ფხვნილს იყენებდნენ ტრადიციულ მედიცინაში ათასობით წლის განმავლობაში. მომდინარეობს Curcuma longa მცენარის ფესვიდან, მას აქვს ტიპიური ყვითელი ფერი და თბილი, ოდნავ მწარე გემო. ზერდა შეიცავს ნაერთს, სახელად კურკუმინს, რომელიც პასუხისმგებელია ჯანმრთელობის ბევრ სარგებელზე. კურკუმას ფხვნილის ჯანმრთელობის გაუმჯობესების ეფექტებია: ანთების საწინააღმდეგო თვისებები: კურკუმაში შემავალ კურკუმინს აქვს ძლიერი ანთების საწინააღმდეგო თვისებები, რაც ხელს უწყობს ორგანიზმში ანთების შემცირებას. ქრონიკული ანთება დაკავშირებულია ბევრ დაავადებასთან, მათ შორის გულის დაავადებებთან, დიაბეტთან და კიბოს ზოგიერთ სახეობასთან. ანტიოქსიდანტური ეფექტები: კურკუმას ფხვნილი მდიდარია ანტიოქსიდანტებით, რაც დაგეხმარებათ დაიცვას თქვენი უჯრედები თავისუფალი რადიკალების დაზიანებისგან. თავისუფალი რადიკალები არასტაბილური მოლეკულებია, რომლებსაც შეუძლიათ გამოიწვიონ ოქსიდაციური სტრესი და ხელი შეუწყონ ქრონიკულ დაავადებას. შეუძლია დაეხმაროს გულის დაავადების რისკის შემცირებას: კურკუმაში შემავალ კურკუმინს შეუძლია გააუმჯობესოს გულის ჯანმრთელობა ანთების შემცირებით, სისხლის მიმოქცევის გაუმჯობესებით და სისხლის შედედების რისკის შემცირებით. შეუძლია დაეხმაროს ართრიტის მართვას: Zerma-ს შეუძლია შეამციროს სახსრების ტკივილი და შეშუპება ართრიტის მქონე ადამიანებში. ზოგიერთმა კვლევამ აჩვენა, რომ ისინი შეიძლება იყოს ისეთივე ეფექტური, როგორც არასტეროიდული ანთების საწინააღმდეგო საშუალებები (არასტეროიდული ანთების საწინააღმდეგო საშუალებები) ართრიტის სიმპტომების მართვაში. შეუძლია გააუმჯობესოს ტვინის ფუნქცია: კურკუმაში შემავალ კურკუმინს შეუძლია გააუმჯობესოს ტვინის ფუნქცია ნეიროტროფული ფაქტორიდან (BDNF) მიღებული ცილის დონის გაზრდით, რაც მნიშვნელოვანია ტვინის ფუნქციონირებისთვის და შეუძლია როლი ითამაშოს ალცჰეიმერის დაავადების განვითარებასთან ბრძოლაში.",
    descriptionEng: "Turmeric powder has been used in traditional medicine for thousands of years, especially in India and other parts of Asia. Derived from the root of the Curcuma longa plant, it has a typical yellow color and a warm, slightly bitter taste. Zerda contains a compound called curcumin, which is responsible for many health benefits. Some of the health benefits of turmeric powder are: Anti-inflammatory properties: Curcumin in turmeric has powerful anti-inflammatory properties that can help reduce inflammation in the body. Chronic inflammation is linked to many diseases, including heart disease, diabetes and some types of cancer. Antioxidant Effects: Turmeric powder is rich in antioxidants, which can help protect your cells from free radical damage. Free radicals are unstable molecules that can cause oxidative stress and contribute to chronic disease.",
    quantity: 1,
    category: "Powder",
  },
  {
    id: "Detox-Tea",
    nameGeo: "დეტოქსის ჩაი",
    nameEng: "Detox Tea",
    price: "40.00",
    images: [
      "https://i.postimg.cc/15S7mB3s/pebblely.jpg",
      "https://i.postimg.cc/2jhXNMm0/pebblely-1.jpg",
      "https://i.postimg.cc/5yBP5Yph/pebblely-2.jpg",
      "https://i.postimg.cc/PJY76FfF/pebblely-6.jpg",

    ],
    inStock: 2,
    fastDelivery: false,
    ratings: 4,
    descriptionGeo:"დეტოქსის ჩაის მთავარი დანიშნულებაა გაწმინდოს თქვენი რესპირატორული ორგანოები წლების მანძილზე დალექილი ქიმიური ნარევებისგან (საუკეთესოა მწეველებისთვის), ჩვენს პროდუქტს შეუძლია წლების მანძილზე დალექილი ქიმიური ნარჩენები, იქნება ეს სიგარეტის ნარჩენი ქიმიური ნალექი, გამონაბოლქვისგან მიღებული მავნე ქიმიური ნივთიერებები თუ სხვა გამოიტანოს ფილტვებიდან და გაწმინდოს თქვენი სასუნთქი სისტემა. ჩვენი ჩაის ბლენდი ასევე ამსუბუქებს გაციების სიმფტომებს, ხდის ორგანიზმს უფრო ენერგიულს და აძლიერებს იმუნურ სისტემას. ჩაი ასევე გამოირჩევა სასიამოვნო გემოთი და ინფლამაციასთან საბრძოლველი თვისებებით, ამსუბუქებს ხველების პრობლემას და ასუფთავებს სასუნთქ გზებს, აგრეთვე მნიშვნელოვნად ამცირებს სიცოცხლისთვის საშიში რესპირატორული დაავადებების შეძენის ალბათობას. ",
    descriptionEng:"The main objective of Detox Tea is to cleanse your respiratory organs of chemical compounds that have accumulated over the years (best for smokers) Our tea blend also relieves cold symptoms, makes the body more energetic and strengthens the immune system. Tea also has anti-inflammatory properties, relieves coughs and clears the respiratory routes.",
    quantity: 1,
    category: "Tea",
  },
  
  
];
